# Generated by Django 5.2.5 on 2025-08-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_discount_tax_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='name',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='stripe_coupon_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='stripe_tax_rate_id',
        ),
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR')], max_length=3),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
