# Generated by Django 5.2.5 on 2025-08-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_discount_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='stripe_coupon_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='stripe_tax_rate_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
